inherits:
  - strictness_veryhigh.yaml

test-warnings: true

doc-warnings: false

pep8:
  options:
    max-line-length: 120

pylint:
  disable:
    - line-too-long  # Already checked by pep8
