name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python '3.7'
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Style check
      run: |
        black . --check --color --diff --target-version py37
    - name: Lint
      run: |
        prospector
    - name: Test
      run: |
        pytest
